### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by rusnazip** [shibajee/openwrt-realtek#1]
i have error then try make
xgcc: error: unrecognized argument in option '-march=lexra'
how i can fix it?

**Comment by shibajee** [comment]
> i have error then try make
> xgcc: error: unrecognized argument in option '-march=lexra'
> how i can fix it?

use gcc 8.3, binutils 2.32 in make menuconfig @rusnazip

**Comment by rusnazip** [comment]
I can't find where to put it in menuconfig =(

**Comment by rusnazip** [comment]
I try it, thx =)
