### ISSUE TITLE
Router support

### ISSUE THREAD

**Issue by rusnazip** [shibajee/openwrt-realtek#2]
Can I adapt the build to the TOTOLINK a3002ru router? Is there a driver for realtek RTL8197DN?

**Comment by shibajee** [comment]
nope u can't, this one only supports RTL8196E/C...it doesn't have the necessary codes for 8197..u can download rtk_openwrtSDK_v2.5 from [here](https://sourceforge.net/projects/rtl819x/files/) , it has precompiled firmware image for RTL8197DN @rusnazip

**Comment by rusnazip** [comment]
thx
